/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: n3A1TPm8pXJ+ZdRV2bJXf78s1StfE71a1o2Bx8D4QRAWAvEk81YKqNXUFqqZa9faW/2y7N+LVX6oMETKNXlbJw==
 */

/* eslint-disable */
// tslint:disable

interface Departments {
  description: (string) | null
  id: number & {readonly __brand?: 'departments_id'}
  name: string
}
export default Departments;

interface Departments_InsertParameters {
  description?: (string) | null
  id: number & {readonly __brand?: 'departments_id'}
  name: string
}
export type {Departments_InsertParameters}
