/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: jEoTdl2Ruak26bp+V1hEWCS736/yxNMCfCMcoCpNNgUynzVLVhg1sea/MX+EV4J9i4ay22us7aL0etucsU/m3w==
 */

/* eslint-disable */
// tslint:disable

interface Users {
  department: string
  email: string
  firstName: string
  id: number & {readonly __brand?: 'users_id'}
  image: (string) | null
  lastName: string
  title: (string) | null
}
export default Users;

interface Users_InsertParameters {
  department: string
  email: string
  firstName: string
  id: number & {readonly __brand?: 'users_id'}
  image?: (string) | null
  lastName: string
  title?: (string) | null
}
export type {Users_InsertParameters}
